=== MaitaneGomez/tuttoverdi2010/RehearsalReservationCore/src/rehearsalServer/saxParser/gateway.dtd
<!--GATEWAY elemento principal-->
<!ELEMENT gateway (service+)>


<!--SERVICE-->
<!ELEMENT service (serviceName, details, tech)>


<!ELEMENT serviceName (#PCDATA)>
<!ELEMENT tech (#PCDATA)>


<!--DETAILS-->
<!ELEMENT details (detail+)>
<!ELEMENT detail EMPTY>
<!ATTLIST detail name CDATA #REQUIRED>

=== MaitaneGomez/tuttoverdi2010/RehearsalReservationCore/src/rehearsalServer/saxParser/gateway.xml
<?xml version="1.0"?>



	<!DOCTYPE gateway SYSTEM "gateway.dtd">


<gateway>
	<service>
		<serviceName>ScalaMILANO</serviceName>
		<details>
			<detail name="127.0.0.1"/>
			<detail name="900"/>
		</details>
		<tech>corba</tech>
	</service>
	
	<service>
		<serviceName>RoyalOperaLondon</serviceName>
		<details>
			<detail name="queueJMS"/>
		</details>
		<tech>jms</tech>
	</service>
	
	<service>
		<serviceName>sanCarloNapoli</serviceName>
		<details>
			<detail name="127.0.0.1"/>
			<detail name="900"/>
		</details>
		<tech>corba</tech>
	</service>
	
	<service>
		<serviceName>EuskaldunaBio</serviceName>
		<details>
			<detail name="http://127.0.0.1:8080/axis2/services/EuskaldunaBio"/>
		</details>
		<tech>ws</tech>
	</service>	
</gateway>
